// Loot Table Modification

LootJS.modifiers((event) => {
    // Loot Table minecraft:desert_pyramid
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("minecraft:diamond_chestplate")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.3).addLoot("minecraft:golden_chestplate")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.2).addLoot("minecraft:iron_chestplate")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.2).addLoot("minecraft:blaze_powder").limitCount([1, 2])
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("minecraft:diamond_sword")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.3).addLoot("minecraft:iron_sword")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.5).addLoot("minecraft:ancient_debris").limitCount([1, 10])
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("dungeons_plus:warped_axe")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("minecraft:blaze_rod")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.4).addLoot("minecraft:ender_pearl").limitCount([1, 2])
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("armoroftheages:anubis_armor_head")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("armoroftheages:anubis_armor_chest")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("armoroftheages:anubis_armor_legs")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("armoroftheages:anubis_armor_feet")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("armoroftheages:pharaoh_armor_head")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("armoroftheages:pharaoh_armor_chest")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("armoroftheages:pharaoh_armor_legs")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.1).addLoot("armoroftheages:pharaoh_armor_feet")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.2).addLoot("armoroftheages:centurion_armor_head")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.2).addLoot("armoroftheages:centurion_armor_chest")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.2).addLoot("armoroftheages:centurion_armor_legs")
    event.addLootTableModifier("minecraft:chests/desert_pyramid").randomChance(0.2).addLoot("armoroftheages:centurion_armor_feet")

    event.addLootTableModifier("minecraft:chests/desert_pyramid").removeLoot('minecraft:diamond_horse_armor')
    event.addLootTableModifier("minecraft:chests/desert_pyramid").removeLoot('minecraft:golden_horse_armor')
    event.addLootTableModifier("minecraft:chests/desert_pyramid").removeLoot('minecraft:iron_horse_armor')
    event.addLootTableModifier("minecraft:chests/desert_pyramid").removeLoot('minecraft:rotten_flesh')
    event.addLootTableModifier("minecraft:chests/desert_pyramid").removeLoot('minecraft:sand')
    event.addLootTableModifier("minecraft:chests/desert_pyramid").removeLoot('minecraft:bone')
    event.addLootTableModifier("minecraft:chests/desert_pyramid").removeLoot('minecraft:string')
    event.addLootTableModifier("minecraft:chests/desert_pyramid").removeLoot('minecraft:spider_eye')

    // Loot Table
    event.addLootTableModifier("minecraft:chests/lootb").randomChance(0.5).addLoot("minecraft:iron_ingot").limitCount([1, 4])
    event.addLootTableModifier("minecraft:chests/simple_dungeon").randomChance(0.5).addLoot("minecraft:gold_ingot").limitCount([1, 4])
    event.addLootTableModifier("minecraft:chests/simple_dungeon").randomChance(0.2).addLoot("minecraft:iron_chestplate")
    event.addLootTableModifier("minecraft:chests/simple_dungeon").randomChance(0.4).addLoot("minecraft:chainmail_chestplate")
    event.addLootTableModifier("minecraft:chests/simple_dungeon").randomChance(0.1).addLoot("legendary_monsters:eye_of_sandstorm")
    event.addLootTableModifier("minecraft:chests/village/village_desert_house").randomChance(0.5).addLoot(Item.of('minecraft:potion', '{Potion:"minecraft:water"}')).limitCount([1, 4])
    event.addLootTableModifier("revampedvillages:desert_common").randomChance(0.5).addLoot(Item.of('minecraft:potion', '{Potion:"minecraft:water"}')).limitCount([1, 4])
    event.addLootTableModifier("explorify:chest/supply_cache").randomChance(0.5).addLoot(Item.of('minecraft:potion', '{Potion:"minecraft:water"}')).limitCount([1, 4])
    event.addLootTableModifier("explorations:chests/desert_ruin").randomChance(0.5).addLoot(Item.of('minecraft:potion', '{Potion:"minecraft:water"}')).limitCount([1, 4])
    event.addLootTableModifier("formationsoverworld:desert_houses").randomChance(0.5).addLoot(Item.of('minecraft:potion', '{Potion:"minecraft:water"}')).limitCount([1, 4])
    event.addLootTableModifier("repurposed_structures:chests/outposts/desert").randomChance(0.5).addLoot(Item.of('minecraft:potion', '{Potion:"minecraft:water"}')).limitCount([1, 4])
    event.addLootTableModifier("repurposed_structures:chests/outposts/desert").randomChance(0.5).addLoot("minecraft:spectral_arrow").limitCount([1, 6])
    event.addLootTableModifier("repurposed_structures:chests/outposts/desert").randomChance(0.5).addLoot("minecraft:gold_ingot").limitCount([1, 4])
    event.addLootTableModifier("minecraft:entities/rabbit").randomChance(1).addLoot("rabbit_hide")
    
    event.addLootTableModifier("minecraft:chests/desert_pyramid").removeLoot('minecraft:spider_eye')
    event.addLootTableModifier("minecraft:chests/lootb").removeLoot('minecraft:honey_bottle')
    event.addLootTableModifier("minecraft:chests/simple_dungeon").removeLoot('farmersdelight:rope')
    event.addLootTableModifier("minecraft:chests/simple_dungeon").removeLoot('farmersdelight:cabbage_seeds')
    event.addLootTableModifier("minecraft:chests/simple_dungeon").removeLoot('farmersdelight:tomato_seeds')
    event.addLootTableModifier("minecraft:chests/simple_dungeon").removeLoot('minecraft:pumpkin_seeds')
    event.addLootTableModifier("minecraft:chests/simple_dungeon").removeLoot('minecraft:beetroot_seeds')
    event.addLootTableModifier("minecraft:chests/simple_dungeon").removeLoot('minecraft:melon_seeds')
    event.addLootTableModifier("minecraft:chests/simple_dungeon").removeLoot('minecraft:rotten_flesh')
    event.addLootTableModifier("minecraft:chests/simple_dungeon").removeLoot('minecraft:wheat')
    event.addLootTableModifier("minecraft:chests/simple_dungeon").removeLoot('minecraft:redstone')
    event.addLootTableModifier("betterarcheology:chest_buried_ruins_sand").removeLoot('minecraft:fermented_spider_eye')
    event.addLootTableModifier("repurposed_structures:chests/outposts/desert").removeLoot('minecraft:cactus')
    event.addLootTableModifier("formationsoverworld:desert_houses").removeLoot('minecraft:glass_bottle')
});